// Josh's project universe, ported from "The Parris Quilt" (master:index.html, commit 6e47ae6).
// Shown in the Project Quilt tab. THREADS are the 50 conversations the brief turns into quests;
// docs/THREADS.md maps each one to the storylets that tell it.

export type ProjectType = "game" | "hub" | "archive" | "app" | "tool";

export interface Project {
  name: string;
  type: ProjectType;
  desc?: string;
  play?: string;
  repo: string;
  featured?: boolean;
}

export const PROJECTS: Project[] = [
  { name: "Buckland Blocks", type: "game", desc: "Voxel sandbox: exploration, building, inventory and crafting.", play: "https://buckland-blocks.vercel.app/", repo: "https://github.com/Parris-Tech-Services/BucklandBlocks", featured: true },
  { name: "The Hollow Marches", type: "game", desc: "AI fantasy RPG with quests, combat, levelling and persistent saves.", play: "https://astra-dnd-game.vercel.app/", repo: "https://github.com/Parris-Tech-Services/AstraDndGame", featured: true },
  { name: "Car Builder + Racing", type: "game", desc: "Build, tune, save and race custom cars.", play: "https://topsecretcheese-del.github.io/carGame/", repo: "https://github.com/topsecretcheese-del/carGame", featured: true },
  { name: "Grandmaster Path", type: "game", desc: "Chess practice, bots, puzzles, lessons and analysis.", play: "https://chess-kappa-five.vercel.app/", repo: "https://github.com/Parris-Tech-Services/Chess", featured: true },
  { name: "Lantern Road", type: "game", desc: "Party adventure across a hex frontier with quests and compact battles.", play: "https://parris-tech-services.github.io/lantern-road/", repo: "https://github.com/Parris-Tech-Services/lantern-road", featured: true },
  { name: "Breach Command", type: "game", desc: "Turn-based tactical browser roguelike.", play: "https://parris-tech-services.github.io/breach-command/", repo: "https://github.com/Parris-Tech-Services/breach-command", featured: true },
  { name: "Whispering Wilds", type: "game", desc: "Text-first wilderness RPG with branching quests and autosaves.", play: "https://parris-tech-services.github.io/WhirringWilderness/", repo: "https://github.com/Parris-Tech-Services/WhirringWilderness", featured: true },
  { name: "Wastes Courier", type: "game", desc: "Browser roguelike about surviving and travelling through the wastes.", play: "https://wastes-courier-roguelike.vercel.app/", repo: "https://github.com/Parris-Tech-Services/wastes-courier-roguelike", featured: true },
  { name: "Eleven Realms", type: "game", desc: "Compact exploration realms, relics, gates and score chasing.", play: "https://realms-bay.vercel.app/", repo: "https://github.com/Parris-Tech-Services/Eleven-Realms", featured: true },
  { name: "NeathBound", type: "game", desc: "Choice-heavy storylets, qualities, menaces and the first doorway into the Beneath.", play: "https://parris-tech-services.github.io/NeathBound/", repo: "https://github.com/Parris-Tech-Services/NeathBound", featured: true },
  { name: "The Consultancy Beneath", type: "game", desc: "A separate story-world that now looks suspiciously connected.", play: "https://joshualparris.github.io/the-consultancy-beneath/", repo: "https://github.com/joshualparris/the-consultancy-beneath", featured: true },
  { name: "JoshHub", type: "hub", desc: "The existing game and app hub: an earlier map of the quilt.", play: "https://josh-hub-two.vercel.app/games", repo: "https://github.com/joshualparris/JoshHub", featured: true },
  { name: "JoshMemory", type: "archive", desc: "A memory and project archive that remembers what individual apps forget.", play: "https://joshualparris.github.io/JoshMemory/", repo: "https://github.com/joshualparris/JoshMemory", featured: true },
  { name: "DCSPD", type: "app", desc: "Professional development and school-support project.", play: "https://dcspd.vercel.app/", repo: "https://github.com/Parris-Tech-Services/DCSPD" },
  { name: "AI Dungeon Master", type: "game", desc: "AI-assisted dungeon-master experiment and ancestor of later RPG work.", play: "https://ai-dungeon-master-azure.vercel.app/", repo: "https://github.com/parristechservices-prog/AIDungeonMaster" },
  { name: "Energy Quest", type: "game", repo: "https://github.com/Parris-Tech-Services/energyquest" },
  { name: "Max", type: "game", repo: "https://github.com/Parris-Tech-Services/Max" },
  { name: "LifeHub Dashboard", type: "app", repo: "https://github.com/Parris-Tech-Services/lifehubdashboard" },
  { name: "Buckland Blocks 1", type: "game", repo: "https://github.com/Parris-Tech-Services/BucklandBlocks1" },
  { name: "Campaign Copilot", type: "app", repo: "https://github.com/Parris-Tech-Services/campaign-copilot" },
  { name: "DCS Companion", type: "app", repo: "https://github.com/Parris-Tech-Services/DCSCompanion" },
  { name: "Midnight Line", type: "game", repo: "https://github.com/Parris-Tech-Services/Midnight-Line" },
  { name: "DCS Prep", type: "app", repo: "https://github.com/Parris-Tech-Services/DCSPrep" },
  { name: "Josh NFC Audio", type: "app", repo: "https://github.com/Parris-Tech-Services/JoshNFCAudio" },
  { name: "Random Play", type: "game", repo: "https://github.com/Parris-Tech-Services/random-play" },
  { name: "StarHaven", type: "game", repo: "https://github.com/Parris-Tech-Services/StarHaven" },
  { name: "Josh Coach", type: "app", repo: "https://github.com/Parris-Tech-Services/JoshCoach" },
  { name: "Wild2", type: "game", repo: "https://github.com/Parris-Tech-Services/Wild2" },
  { name: "ClearCore", type: "app", repo: "https://github.com/Parris-Tech-Services/ClearCore" },
  { name: "LifeHub", type: "app", repo: "https://github.com/Parris-Tech-Services/LifeHub" },
  { name: "Parris Piano", type: "app", repo: "https://github.com/Parris-Tech-Services/ParrisPiano" },
  { name: "GoldFinder", type: "app", repo: "https://github.com/Parris-Tech-Services/GoldFinder" },
  { name: "Josh Fire Awareness", type: "app", repo: "https://github.com/Parris-Tech-Services/JoshFireAwareness" },
  { name: "Sword Coast", type: "game", repo: "https://github.com/Parris-Tech-Services/SwordCoast" },
  { name: "KKC Adventure", type: "game", repo: "https://github.com/Parris-Tech-Services/kkc-adventure" },
  { name: "Rothfuss KKC Adventure", type: "game", repo: "https://github.com/Parris-Tech-Services/rothfuss-kkc-adventure" },
  { name: "NebulaDice Browser", type: "game", repo: "https://github.com/Parris-Tech-Services/NebulaDice-Browser" },
  { name: "Elodin Deep Lore", type: "game", repo: "https://github.com/Parris-Tech-Services/ElodinDeepLore" },
  { name: "Elodin Deep Lore II", type: "game", repo: "https://github.com/Parris-Tech-Services/elodin-deep-lore" },
  { name: "Ashfaller", type: "game", repo: "https://github.com/Parris-Tech-Services/ashfaller" },
  { name: "Echo", type: "game", repo: "https://github.com/Parris-Tech-Services/Echo" },
  { name: "Delve", type: "game", repo: "https://github.com/Parris-Tech-Services/delve" },
  { name: "Marsh", type: "game", repo: "https://github.com/Parris-Tech-Services/Marsh" },
  { name: "Rothfuss Maps", type: "app", repo: "https://github.com/Parris-Tech-Services/RothfussMaps" },
  { name: "Three Layers", type: "game", repo: "https://github.com/Parris-Tech-Services/3layers" },
  { name: "Alfie", type: "game", repo: "https://github.com/Parris-Tech-Services/alfie" },
  { name: "DCS Professional Development", type: "app", repo: "https://github.com/Parris-Tech-Services/DCSProfessionalDevelopment" },
  { name: "Canon RPG", type: "game", repo: "https://github.com/Parris-Tech-Services/CanonRPG" },
  { name: "Field Notes", type: "app", repo: "https://github.com/Parris-Tech-Services/FieldNotes" },
  { name: "App Factory", type: "tool", repo: "https://github.com/Parris-Tech-Services/AppFactory" },
  { name: "Power App", type: "app", repo: "https://github.com/Parris-Tech-Services/PowerApp" },
  { name: "FaithHub", type: "app", repo: "https://github.com/Parris-Tech-Services/FaithHub" },
  { name: "Exchange Lab Manager", type: "tool", repo: "https://github.com/Parris-Tech-Services/ExchangeLabManager" },
  { name: "Work Planner", type: "app", repo: "https://github.com/Parris-Tech-Services/WorkPlanner" },
  { name: "Work", type: "app", repo: "https://github.com/Parris-Tech-Services/Work" },
  { name: "Josh Platform", type: "hub", repo: "https://github.com/Parris-Tech-Services/JoshPlatform" },
  { name: "Chronicles of the Sword Coast", type: "game", repo: "https://github.com/Parris-Tech-Services/dndgame" },
  { name: "Waypoint", type: "app", repo: "https://github.com/Parris-Tech-Services/Waypoint" },
  { name: "AnchorFlow", type: "app", repo: "https://github.com/Parris-Tech-Services/AnchorFlow" },
  { name: "Skills", type: "app", repo: "https://github.com/Parris-Tech-Services/skills" },
  { name: "Disk Cleanup Audit", type: "tool", repo: "https://github.com/Parris-Tech-Services/DiskCleanupAudit" },
  { name: "Hermes Control", type: "tool", repo: "https://github.com/Parris-Tech-Services/HermesControl" },
  { name: "Josh Books Online", type: "app", repo: "https://github.com/Parris-Tech-Services/JoshBooksOnline" },
  { name: "Josh Chess", type: "game", repo: "https://github.com/Parris-Tech-Services/JoshChess" },
  { name: "EPUB Translate", type: "tool", repo: "https://github.com/Parris-Tech-Services/epubtranslate" },
  { name: "Carl", type: "game", repo: "https://github.com/Parris-Tech-Services/carl" },
  { name: "Josh Cards", type: "app", repo: "https://github.com/Parris-Tech-Services/JoshCards" },
  { name: "HeartCalm", type: "app", repo: "https://github.com/Parris-Tech-Services/HeartCalm" },
  { name: "Drifter", type: "game", repo: "https://github.com/Parris-Tech-Services/drifter" },
  { name: "Lore", type: "game", repo: "https://github.com/Parris-Tech-Services/lore" },
  { name: "Aetheria", type: "game", repo: "https://github.com/Parris-Tech-Services/Aetheria" },
  { name: "Dinner Decider", type: "app", repo: "https://github.com/Parris-Tech-Services/Dinner-Decider" },
  { name: "Game Booster", type: "tool", repo: "https://github.com/Parris-Tech-Services/Game-Booster" },
  { name: "JoshBIOS", type: "tool", repo: "https://github.com/Parris-Tech-Services/JoshBIOS" },
  { name: "NextJS Expert", type: "tool", repo: "https://github.com/Parris-Tech-Services/NextJS-Expert" },
  { name: "Prompt Linker", type: "tool", repo: "https://github.com/Parris-Tech-Services/Prompt-Linker" },
  { name: "Serenity: Keep Flying", type: "game", repo: "https://github.com/Parris-Tech-Services/Serenity-Keep-Flying" },
  { name: "Cold Flu App", type: "app", repo: "https://github.com/Parris-Tech-Services/ColdFluApp" },
  { name: "LLM Accountability", type: "tool", repo: "https://github.com/Parris-Tech-Services/LLMAccountability" },
  { name: "Fedora Crash Doctor", type: "tool", repo: "https://github.com/Parris-Tech-Services/FedoraCrashDoctor" },
  { name: "Kaseya Field Ops", type: "app", repo: "https://github.com/Parris-Tech-Services/KaseyaFieldOps" },
  { name: "Whispering Wilds (original)", type: "game", repo: "https://github.com/joshualparris/Whispering-Wilds" },
  { name: "Josh Tap App", type: "app", repo: "https://github.com/joshualparris/JoshTapApp" },
  { name: "AshFallen", type: "game", repo: "https://github.com/joshualparris/AshFallen" },
  { name: "Sylvie Phonetics", type: "app", repo: "https://github.com/joshualparris/SylviePhonetics" },
  { name: "HealthLens", type: "app", repo: "https://github.com/joshualparris/HealthLens" },
  { name: "Paul Roe Archive", type: "archive", repo: "https://github.com/joshualparris/Paul-Roe" },
  { name: "Buckland Blocks Demo", type: "game", repo: "https://github.com/joshualparris/buckland-blocks-demo" },
  { name: "Cheap PCs & Laptops", type: "app", repo: "https://github.com/joshualparris/Cheappcslaptops" },
  { name: "JoshOS", type: "tool", repo: "https://github.com/joshuaparris-max/JoshOS" },
  { name: "Greg Game", type: "game", repo: "https://github.com/topsecretcheese-del/gregGame" },
  { name: "Custom Cars", type: "game", repo: "https://github.com/topsecretcheese-del/customCars" },
  { name: "SIGNAL BENEATH", type: "game", desc: "You are here. The stitch connecting the quilt.", repo: "https://github.com/Parris-Tech-Services/awdagaer", featured: true },
];

/** [title, lesson], numbered 1–50 in this order. */
export const THREADS: ReadonlyArray<readonly [string, string]> = [
  ["DBO1-SIM", "A training simulation generates a scenario nobody authored."],
  ["Google Won’t Load", "The browser is innocent. Follow DNS."],
  ["The Finished Series", "Never invent where somebody is up to."],
  ["The LANCache Incident", "Global DNS before local verification breaks the household."],
  ["The Chemist Shelf", "Marketing words are not ingredients."],
  ["Build the Cache", "Verify, test one client, keep rollback."],
  ["Flickering Steam", "A fix is not finished until it persists."],
  ["169.254", "A machine asks DHCP and hears nothing."],
  ["The Loud Switches", "Throughput, fans, heat and trade-offs."],
  ["404 Recovery", "The internet forgets old tools."],
  ["Benchmarks", "Compare hardware from evidence, not vibes."],
  ["Disclosure Gap", "Event, discovery, understanding and disclosure are different dates."],
  ["Chrome Again", "Repeated symptoms deserve remembered causes."],
  ["The Nasal Spray", "Words like steroid need context, not panic."],
  ["The Choice Game", "Popularity and relevance are not the same."],
  ["Staff Health", "Memory is not verification."],
  ["Inventory Day", "Give every machine a name and provenance."],
  ["Updates Paused", "A friendly button can hide a hostile policy."],
  ["Policy Cleanup", "Remove the cause, not just the symptom."],
  ["Stop Auto Login", "Convenience is also a trust boundary."],
  ["Vale", "Respect uncertainty when facts are absent."],
  ["The Missing Artwork", "A green build can still ship a broken experience."],
  ["The Certificate", "Institutional knowledge is infrastructure."],
  ["Anatomy of a Storylet", "A paragraph plus meaningful choices can carry a world."],
  ["What Is NeathBound?", "One dead anchor can break the doorway."],
  ["Unique Location Artwork Done", "Reconstruct lost context from surviving evidence."],
  ["Twenty-Two Choices", "Play every branch; interfaces can lie about mechanics."],
  ["The Conversation That Wouldn’t Open", "One lost record should not erase the project."],
  ["Right Person, Right Medication", "Identity errors matter."],
  ["Banana Pancakes", "A small family action can beat a large technical win."],
  ["DNS Again", "When context is known, take the shortest safe path."],
  ["Address History", "Digital identities outlive the people using them."],
  ["False Attribution", "Wrong evidence removed is progress."],
  ["Mini", "A companion should know only what it is given."],
  ["Hepatitis Clearance", "Evidence of immunity is not evidence of dose history."],
  ["Oldest Thing", "Every archive has a floor."],
  ["Missed Dose", "Time-sensitive questions need the right person and record."],
  ["RATS", "Turn messy communication into an action."],
  ["Release Gate", "Regression prevention becomes infrastructure."],
  ["Chunk Revision", "State must survive the world changing around it."],
  ["Offline Means Offline", "Test the actual promise."],
  ["The Missing Audio", "Do not fabricate what cannot be recovered."],
  ["SSD Allocation", "Scarce upgrades reveal priorities."],
  ["The Boarding House", "Policy, pay, accommodation and reality overlap."],
  ["Closed Sunday", "A nearby resource is useless when unavailable."],
  ["The Consultancy Beneath", "A route fix uncovers a name."],
  ["Graphics Could Not Start", "Visible failure is kinder than a black screen."],
  ["Chooky Dancers", "Preserve provenance even when the media is gone."],
  ["Forensic Audit", "Software evidence can identify almost an entire machine."],
  ["The New Machine", "Correcting an earlier identification strengthens the record."],
];
