// Prints docs/THREADS.md: which storylets tell each of the 50 threads.
// Regenerate with: npm run docs:threads
import { ALL_STORYLETS } from "../src/content";
import { THREADS } from "../src/content/quilt";

const where = new Map<number, Set<string>>();
for (const st of ALL_STORYLETS)
  for (const c of st.choices)
    for (const o of [c.success, c.failure])
      for (const e of o?.effects ?? [])
        if (e.kind === "setQuality" && e.key.startsWith("thread:")) {
          const n = Number(e.key.slice(7));
          if (!where.has(n)) where.set(n, new Set());
          where.get(n)!.add(`\`${st.id}\` (${st.region})`);
        }

const lines = [
  "# The 50 Threads",
  "",
  "The brief asks for \"50 conversations\" to become connected parts of one RPG. They are the 50 `THREADS` from The Parris Quilt (`src/content/quilt.ts`, originally `master:index.html`). Each row lists the storylets whose outcomes mark that thread as discovered (quality `thread:N`), shown in the in-game **Threads** tab.",
  "",
  "_Generated by `npm run docs:threads`. Do not edit by hand._",
  "",
  "| # | Thread | Lesson | Told by |",
  "|---|---|---|---|",
  ...THREADS.map(([title, lesson], i) => `| ${i + 1} | ${title} | ${lesson} | ${[...(where.get(i + 1) ?? [])].join(", ") || "**not yet in game**"} |`),
  "",
];
process.stdout.write(lines.join("\n"));
